### PR TITLE
Switch to YAML for content parsing

### PR DESCRIPTION
**Pull request by Sija**
Hi!

I thought it might a welcomed change over the way the content files are parsed right now. YAML seems as better choice because of it's terseness (no more redundant -- lines), ability for handling more complex value types (arrays, objects, ...) and being de facto standard for a "readable json style" format is not yet-another-meta-language to remember :)

### CODE REVIEW

**Comment by kolber** [comment]
This is great work Sija.
I have been trying to decide whether or not to switch the text files syntax over to yaml for quite some time.

I will pull in your changes and have a play around.

**Comment by Sija** [comment]
Great! Have your time with it and tell me if there's anything I should change in case you decide to merge it in.

**Comment by kolber** [comment]
Really great work Sija.
This has now been merged into master.

**Comment by Sija** [comment]
I'm glad I could help and thanks to you for making such a nice contraption :)

**Comment by rnmp** [comment]
Totally awesome. Thank to you guys I'm finally having my website (http://bandd.co/). YAML helped me a lot.

**Pull request closed without merging**
