### PR TITLE
Selectively turn off caching per page.

### PR DESCRIPTION
**Pull request by michaelsmanley**
I was attempting to make Contacular, and small PHP scripts in general, work in partials. I added the patch from https://github.com/nacholabs/stacey/commit/aab941eb072ea52685966575b939fa5bc6e055c8 

So far, so good. 

However, since Stacey caches the entire page output and does not distinguish the output of partials, that means that any PHP-generated partial will only ever be run once between cache expirations. This is actually fine for most everything you'd want in a Stacey-managed site, I figure, but there are cases when you need the PHP partial to be called on every request. Using Contacular for a contact form -- as described at http://getsatisfaction.com/stacey/topics/managed_to_get_contact_form_working_using_contacular_with_stacey -- is one of those cases. I think you want to keep page caching on for the majority of cases (the default behavior) and be explicit when you want caching turned off for a page.

Rather than go through the messy AJAX solution proposed on GetSatisfaction, I thought it would be simpler to just add a special variable -- @cache_page -- to the system and have its behavior change nothing for the vast majority of pages served up by Stacey. 

In any content file, if you would like the page to _not_ be cached, you can set a variable "cache_page" to something false (0 or blank). When this is done, the rendered output for that page will not be written to the cache, and will be re-rendered on every request.

<pre>
cache_page: 0
-
</pre>

If @cache_page is not defined by a page, or if it is defined and set to anything that evaluates to true, caching is applied to that page. This means that for all existing pages that are already cached, no changes need to be made.

This is not something I would do very often at all on a Stacey site, but for some small set of cases (only one page on my site, for example), it does the trick.

If you look at the 7009cac98cb31f4c59e9 commit, you can see that it is really only a two-line change to the application. There's a change to get_current_hash() that I was missing in my 2.2.2 install.

Thanks for writing Stacey. I like it very much. This is my first time using git/github and making a pull request. If I've done anything wrong, let me know.

MSM
http://michaelsmanley.com/

### CODE REVIEW

**Comment by kolber** [comment]
I like this idea.
Although, wouldn't it be better to do this the other way around? So, only bypass the cache if an `@bypass_cache` variable (or similar) is set?

That way people wouldn't be required to have a `@cache_page` variable in every single text file.

**Comment by michaelsmanley** [comment]
That's basically what is there now. You _don't_ have to set the variable unless you want to explicitly turn caching off. I didn't want to add the variable to every one of my site's pages, so I set it up so that setting it is only for the exceptions.

It would be easy enough to change the semantics so that the variable is "do_not_cache" and set to true for the exceptions, instead of "cache_page" set to false for the exceptions.

**Comment by kolber** [comment]
Wouldn't this line mean that unless the `cache_page` variable exists, then the cache would never be written?
https://github.com/michaelsmanley/stacey/commit/7009cac98cb31f4c59e9c5f964436fa46df01329#L0R42

**Comment by michaelsmanley** [comment]
This line https://github.com/michaelsmanley/stacey/commit/7009cac98cb31f4c59e9c5f964436fa46df01329#L1R147

ensures that the variable always exists and is set to true by default.

I'm going to submit a new pull request that reverses the semantics. If a @bypass_cache variable is set in the page and evaluates to true, then the cache write is skipped. Otherwise, cache as normal.

**Pull request closed without merging**
