### PR TITLE
ignore @2x files to prevent dupes in asset collections

### PR DESCRIPTION
**Pull request by interstateone**
just like ignoring _lge or _sml suffixes, ignore @2x images to prevent duplicates and delegate retina support to retina.js (as one example)

### CODE REVIEW

**Comment by gregcoleinfo** [comment]
I am not very familiar with optimizing for retina screens. It is good that you are tackling this issue. Is the "@2x" required for retina assets, or could it stick to the current stacey naming convention and be "_2x".

PS: This is not your fault, but I don't understand why everyone is calling retina images 2x size. The image is actually 4 times larger, each dimension is doubled. Your kb will probably quadruple too. Thanks!

**Comment by interstateone** [comment]
I just chose the native iOS naming convention for retina images, since from my experience that's the most commonly used. Interestingly, Apple uses the "_2x" suffix on their own site. I'm fine using either, so although libraries like retina.js expect @2x, consistency within Stacey may trump that.

As for the naming: I think choosing the ratio of dimensions instead of area is more intuitive because that's usually how images are referenced. e.g. 200x200 px vs 40 000 px. I'm sure someone more authoritative has a better explanation though.

**Comment by gregcoleinfo** [comment]
Cool, maybe Kolber will chime in with his suggestion. Either way it is great to have and to show people how they could start to add their own image suffixes to extend what they want to do with stacey. Thanks

And the image dimension thing I guess will always bother me. I just know that it is 4 times as many pixels and the filesize will probably be 4 times greater. And then if someone asks for an image 2x larger than that, now the image is 16x larger than the original. It just isn't intuitive to me.

**Comment by mjau-mjau** [comment]
Just browsing through some older posts here, and I would like to comment ... Using @2x is an inferior way of managing multiple sizes, especially if you are working with Stacey which includes the SLIR image resizer. For example to reference a normal and retina-image:

< img src="{{ resize_path( image.url, '730', '', '2:1', 95) }}" alt="{{ image.title }}" data-src-retina="{{ resize_path( image.url, '1460', '', '2:1', 85) }}" >

The above code will voids the requirement of managing @2x files in your assets, you will still only have one file. The resulting files will render and save in your Stacey cache. Another benefit is that you don't only need to manage a single file, and can output thumbnail, small, large and retina images from the same file through requests.

Obviously it requires some JS to render the retina-src instead of the src, regardless.

**Comment by interstateone** [comment]
Thanks for the suggestion @suncat100! That definitely looks like a better solution for Stacey.

**Pull request closed without merging**
