### PR TITLE
little tweaks

### PR DESCRIPTION
**Pull request by fibsifan**
PHP 5.5 complains about preg_replace with /e being deprecated
The old `php_fixes` function ignored the ini-timezone

### CODE REVIEW

**Comment by pbatts** [comment]
Fixes in <code>page-data.inc.php</code> breaks generated <code>pg_name</code>

Example page name "Wiring Harness" now appears as "Wiring' '.strtoupper('\1')arness"

Running <code>PHP 5.3.15</code> locally on Mac OS X.

Thanks,

PB

**Comment by pbatts** [comment]
Upon further investigation, I see the trouble I'm having, as described above, is clearly related to my use of underscores in the file name.

Is there a fix for this?

PB

**Comment by kolber** [comment]
Thanks for the heads up @pbatts. I have pushed up a fix for this.

**Comment by pbatts** [comment]
Excellent.

Thanks,

PB

**Pull request merged**
