### PR TITLE
Updates to include css templates and also robots.txt templates

### PR DESCRIPTION
**Pull request by nsfmc**
Hi there!

While i was working on the stacey-html5-boilerplate fork, i ran into some issues because i was hoping to use both robots.txt files and some stacey vars in my css files, so i made these changes to stacey. They're roughly:
1. adding css content-type to stacey.inc.php
2. updating stacey version comments in cache.inc.php to include css files and also
3. adding # comments for text files (in particular, robots.txt)
4. in page-data.inc.php conditionally turning off markdown processing for txt and css files (with the potential to include other parsers for specific content-types here)
5. passing $page around to TemplateParser to turn off escaping @s in txt and css files

arguably the last two are the most controversial, but i needed to get both of them in so that i could make sure that text-ish files get treated correctly and not like html files (point 4 is particularly apparent in robots.txt files, while point 5 is more relevant to turning off @s being escaped incorrectly in css files.

Let me know what you think, or if the coding style is incompatible. I tried to make the changes as obvious (and commit messages clear) and as unobtrusive as possible while respecting your 'house style.'

Thanks for the great platform, 
--marcos

### CODE REVIEW

**Comment by kolber** [comment]
Hey, nice work Marcos.
Could you give me an idea of the content structure you were using alongside these changes?
It would help give me some context as to what you were looking to achieve.

**Comment by nsfmc** [comment]
Sure thing, i just pushed [these templates](http://github.com/nsfmc/stacey/commit/88fbf550531f2dafd1e7068c5445e2d666f2cb86) to my fork.

The net result is, at the least, stylesheet variability from /content and the ability to deal with robots.txt from within /content as well, even if most people are usually serving that content from within /public/docs... If the caching is going on, then the result should be the same as far as performance goes.

**Comment by kolber** [comment]
Ah, cheers. Everything makes a whole lot more sense now.
I have alternative suggestions for the first two commits to simplify things slightly, but the overall fixes are really valuable. You've picked up on a few oversights of mine from focusing too heavily on the html generation side of things, so it's great to get your perspective on it.

Many thanks.

**Comment by nsfmc** [comment]
No worries, i'll fold in the changes and commit everything. Thanks for the feedback!

**Comment by kolber** [comment]
I've made amended versions of your first two commits, and cherry-picked your second two.
http://github.com/kolber/stacey/compare/fc8a446d7a...5e568a156c
Thanks again.

**Pull request closed without merging**
